[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.numpy",
  "python39Packages.dlib",
  "python39Packages.pip",
  "python39Packages.setuptools",
  "python39Packages.wheel",
  "python39Packages.flask",
  "python39Packages.flask-socketio",
  "python39Packages.flask-cors",
  "python39Packages.eventlet",
  "python39Packages.mediapipe",
  "python39Packages.opencv4",
  "python39Packages.qrcode",
  "gcc",
  "pkg-config",
  "mesa",
  "glib"
]

[phases.install]
cmds = [
  "cd PulseQ"
]

[start]
cmd = "cd PulseQ && python server/app.py" 