[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.pip",
  "cmake",
  "gcc",
  "pkg-config",
  "mesa",
  "glib"
]

[phases.install]
cmds = [
  "cd PulseQ",
  "pip3 install --upgrade pip",
  "pip3 install numpy cmake",
  "pip3 install dlib==19.22.0",
  "pip3 install -r requirements.txt"
]

[start]
cmd = "cd PulseQ && python server/app.py" 