[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.numpy",
  "python39Packages.dlib",
  "python39Packages.pip",
  "python39Packages.virtualenv",
  "python39Packages.setuptools",
  "python39Packages.wheel",
  "gcc",
  "pkg-config",
  "mesa",
  "glib"
]

[phases.install]
cmds = [
  "cd PulseQ",
  "python3 -m venv venv --system-site-packages",
  ". venv/bin/activate",
  "python -m ensurepip --upgrade",
  "python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "cd PulseQ && . venv/bin/activate && python server/app.py" 