[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.numpy",
  "python39Packages.dlib",
  "python39Packages.pip",
  "python39Packages.virtualenv",
  "python39Packages.setuptools",
  "gcc",
  "pkg-config",
  "mesa",
  "glib"
]

[phases.install]
cmds = [
  "cd PulseQ",
  "python3 -m venv venv",
  ". venv/bin/activate",
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python get-pip.py",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "cd PulseQ && . venv/bin/activate && python server/app.py" 