[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.numpy",
  "python39Packages.dlib",
  "python39Packages.flask",
  "python39Packages.flask-socketio",
  "python39Packages.flask-cors",
  "python39Packages.eventlet",
  "python39Packages.opencv4",
  "python39Packages.qrcode",
  "gcc",
  "pkg-config",
  "mesa",
  "glib",
  "cmake",
  "protobuf"
]

[phases.install]
cmds = [
  "cd PulseQ",
  "python3 -m pip install --break-system-packages mediapipe"
]

[start]
cmd = "cd PulseQ && python server/app.py" 