[phases.setup]
nixPkgs = [
  "python39",
  "python39Packages.pip",
  "python39Packages.virtualenv",
  "cmake",
  "gcc",
  "pkg-config",
  "mesa",
  "glib"
]

[phases.install]
cmds = [
  "cd PulseQ",
  "python3 -m venv venv",
  ". venv/bin/activate",
  "python -m pip install --upgrade pip",
  "python -m pip install numpy cmake",
  "python -m pip install dlib==19.22.0",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "cd PulseQ && . venv/bin/activate && python server/app.py" 