services:
  - type: web
    name: pulseq
    env: node
    buildCommand: |
      npm install
      apt-get update && apt-get install -y python3 python3-pip python3-opencv libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev
      pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://smartqueue:hMN5zLUlWH2JxBRR@smartqueue.unjf9yz.mongodb.net/?retryWrites=true&w=majority&appName=smartqueue
      - key: FLASK_ENV
        value: production
    healthCheckPath: / 